name             "set-proxy"
maintainer       "Mikahil Vaysman"
maintainer_email "mikhail.vaysman@gmail.com"
license          "BSD License"
description      "Set proxy environment variable and set proxy for apt-get"
long_description "Set proxy environment variable and set proxy for apt-get"
version          "1.0"
supports         "ubuntu"
